#!/bin/bash

ffc -O -l dolfin EField1D.ufl
ffc -O -l dolfin EField2D.ufl
ffc -O -l dolfin EField3D.ufl
ffc -O -l dolfin Potential1D.ufl
ffc -O -l dolfin Potential2D.ufl
ffc -O -l dolfin Potential3D.ufl
ffc -O -l dolfin PotentialDG1D.ufl
ffc -O -l dolfin PotentialDG2D.ufl
ffc -O -l dolfin PotentialDG3D.ufl
ffc -O -l dolfin VarPotential1D.ufl
ffc -O -l dolfin VarPotential2D.ufl
ffc -O -l dolfin VarPotential3D.ufl
ffc -O -l dolfin Energy.ufl
ffc -O -l dolfin ErrorNorm1D.ufl
ffc -O -l dolfin ErrorNorm2D.ufl
ffc -O -l dolfin ErrorNorm3D.ufl
ffc -O -l dolfin ErrorNormVec1D.ufl
ffc -O -l dolfin ErrorNormVec2D.ufl
ffc -O -l dolfin ErrorNormVec3D.ufl
ffc -O -l dolfin Flux.ufl
ffc -O -l dolfin Surface.ufl
ffc -O -l dolfin Volume.ufl
ffc -O -l dolfin Charge.ufl
ffc -O -l dolfin Constraint.ufl
ffc -O -l dolfin Clement1D.ufl
ffc -O -l dolfin Clement2D.ufl
ffc -O -l dolfin Clement3D.ufl
ffc -O -l dolfin Mean1D.ufl
ffc -O -l dolfin Mean2D.ufl
ffc -O -l dolfin Mean3D.ufl
ffc -O -l dolfin EFieldDG01D.ufl
ffc -O -l dolfin EFieldDG02D.ufl
ffc -O -l dolfin EFieldDG03D.ufl
